// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.test.repo;

import com.test.domain.Login;
import com.test.repo.LoginRepository;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.stereotype.Repository;

privileged aspect LoginRepository_Roo_Jpa_Repository {
    
    declare parents: LoginRepository extends JpaRepository<Login, Long>;
    
    declare parents: LoginRepository extends JpaSpecificationExecutor<Login>;
    
    declare @type: LoginRepository: @Repository;
    
}
