// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.test.domain;

import com.test.domain.Login;
import java.util.Date;

privileged aspect Login_Roo_JavaBean {
    
    public Date Login.getLoginTime() {
        return this.loginTime;
    }
    
    public void Login.setLoginTime(Date loginTime) {
        this.loginTime = loginTime;
    }
    
    public String Login.getUserName() {
        return this.userName;
    }
    
    public void Login.setUserName(String userName) {
        this.userName = userName;
    }
    
    public String Login.getAttribute1() {
        return this.attribute1;
    }
    
    public void Login.setAttribute1(String attribute1) {
        this.attribute1 = attribute1;
    }
    
    public String Login.getAttribute2() {
        return this.attribute2;
    }
    
    public void Login.setAttribute2(String attribute2) {
        this.attribute2 = attribute2;
    }
    
    public String Login.getAttribute3() {
        return this.attribute3;
    }
    
    public void Login.setAttribute3(String attribute3) {
        this.attribute3 = attribute3;
    }
    
    public String Login.getAttribute4() {
        return this.attribute4;
    }
    
    public void Login.setAttribute4(String attribute4) {
        this.attribute4 = attribute4;
    }
    
}
