// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.test.domain;

import com.test.domain.Login;
import com.test.domain.LoginDataOnDemand;
import com.test.repo.LoginRepository;
import com.test.service.LoginService;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect LoginDataOnDemand_Roo_DataOnDemand {
    
    declare @type: LoginDataOnDemand: @Component;
    
    private Random LoginDataOnDemand.rnd = new SecureRandom();
    
    private List<Login> LoginDataOnDemand.data;
    
    @Autowired
    LoginService LoginDataOnDemand.loginService;
    
    @Autowired
    LoginRepository LoginDataOnDemand.loginRepository;
    
    public Login LoginDataOnDemand.getNewTransientLogin(int index) {
        Login obj = new Login();
        setAttribute1(obj, index);
        setAttribute2(obj, index);
        setAttribute3(obj, index);
        setAttribute4(obj, index);
        setLoginTime(obj, index);
        setUserName(obj, index);
        return obj;
    }
    
    public void LoginDataOnDemand.setAttribute1(Login obj, int index) {
        String attribute1 = "attribute1_" + index;
        obj.setAttribute1(attribute1);
    }
    
    public void LoginDataOnDemand.setAttribute2(Login obj, int index) {
        String attribute2 = "attribute2_" + index;
        obj.setAttribute2(attribute2);
    }
    
    public void LoginDataOnDemand.setAttribute3(Login obj, int index) {
        String attribute3 = "attribute3_" + index;
        obj.setAttribute3(attribute3);
    }
    
    public void LoginDataOnDemand.setAttribute4(Login obj, int index) {
        String attribute4 = "attribute4_" + index;
        obj.setAttribute4(attribute4);
    }
    
    public void LoginDataOnDemand.setLoginTime(Login obj, int index) {
        Date loginTime = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setLoginTime(loginTime);
    }
    
    public void LoginDataOnDemand.setUserName(Login obj, int index) {
        String userName = "userName_" + index;
        obj.setUserName(userName);
    }
    
    public Login LoginDataOnDemand.getSpecificLogin(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Login obj = data.get(index);
        Long id = obj.getId();
        return loginService.findLogin(id);
    }
    
    public Login LoginDataOnDemand.getRandomLogin() {
        init();
        Login obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return loginService.findLogin(id);
    }
    
    public boolean LoginDataOnDemand.modifyLogin(Login obj) {
        return false;
    }
    
    public void LoginDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = loginService.findLoginEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Login' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Login>();
        for (int i = 0; i < 10; i++) {
            Login obj = getNewTransientLogin(i);
            try {
                loginService.saveLogin(obj);
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            loginRepository.flush();
            data.add(obj);
        }
    }
    
}
