// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.test.service;

import com.test.domain.Login;
import com.test.service.LoginService;
import java.util.List;

privileged aspect LoginService_Roo_Service {
    
    public abstract long LoginService.countAllLogins();    
    public abstract void LoginService.deleteLogin(Login login);    
    public abstract Login LoginService.findLogin(Long id);    
    public abstract List<Login> LoginService.findAllLogins();    
    public abstract List<Login> LoginService.findLoginEntries(int firstResult, int maxResults);    
    public abstract void LoginService.saveLogin(Login login);    
    public abstract Login LoginService.updateLogin(Login login);    
}
