// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.test.service;

import com.test.domain.Login;
import com.test.repo.LoginRepository;
import com.test.service.LoginServiceImpl;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

privileged aspect LoginServiceImpl_Roo_Service {
    
    declare @type: LoginServiceImpl: @Service;
    
    declare @type: LoginServiceImpl: @Transactional;
    
    @Autowired
    LoginRepository LoginServiceImpl.loginRepository;
    
    public long LoginServiceImpl.countAllLogins() {
        return loginRepository.count();
    }
    
    public void LoginServiceImpl.deleteLogin(Login login) {
        loginRepository.delete(login);
    }
    
    public Login LoginServiceImpl.findLogin(Long id) {
        return loginRepository.findOne(id);
    }
    
    public List<Login> LoginServiceImpl.findAllLogins() {
        return loginRepository.findAll();
    }
    
    public List<Login> LoginServiceImpl.findLoginEntries(int firstResult, int maxResults) {
        return loginRepository.findAll(new org.springframework.data.domain.PageRequest(firstResult / maxResults, maxResults)).getContent();
    }
    
    public void LoginServiceImpl.saveLogin(Login login) {
        loginRepository.save(login);
    }
    
    public Login LoginServiceImpl.updateLogin(Login login) {
        return loginRepository.save(login);
    }
    
}
